### ISSUE TITLE
VCF QUAL column is treated as String, should be Numeric.

### ISSUE THREAD

**Issue by fdlk** [molgenis/systemsgenetics#418]
The [specs v4.2](https://samtools.github.io/hts-specs/VCFv4.2.pdf) ([v4.1](http://samtools.github.io/hts-specs/VCFv4.1.pdf) too) say
> QUAL - quality: Phred-scaled quality score for the assertion made in ALT. i.e. −10log10 prob(call in ALT is wrong). If ALT is ‘.’ (no variant) then this is −10log10 prob(variant), and if ALT is not ‘.’ this is −10log10 prob(no variant). If unknown, the missing value should be specified. (Numeric)

But `VcfRecord.getQuality()` returns `String`.

**Comment by PatrickDeelen** [comment]
This is not a bug. In practice this part of the specification is not followed. Converting this to numeric will give problems. User should test if it is save to convert and do so if needed.
