### ISSUE TITLE
Link to JAR dead

### ISSUE THREAD

**Issue by colindaven** [molgenis/systemsgenetics#443]
Hi, 

I am looking to try to find:

cellTypeSpecificAlleleSpecificExpression.jar

The link from the docs goes to a 404 page.

<p>This is the first time we're going to use the program, please <a href="https://github.com/adriaan-vd-graaf/systemsgenetics/blob/master/cellTypeSpecificAlleleSpecificExpression/cellTypeSpecificAlleleSpecificExpression.jar?raw=true">download</a> or build it, currently we use the following filename for the jar:
<code>cellTypeSpecificAlleleSpecificExpression.jar</code></p>

Is it just this section of the code ? Or am I missing something ?
https://github.com/molgenis/systemsgenetics/tree/master/cellTypeSpecificAlleleSpecificExpression/src/test/java/nl/systemsgenetics/cellTypeSpecificAlleleSpecificExpression

Thanks,
Colin

**Comment by adriaan-vd-graaf** [comment]
Dear Colin,

This is a problem at the moment, I made the mistake of adding the jar to the git repo, but this was not smart to do. I haven't updated the documentation. Currently I can give you two options, I can send you a compiled jar, or you can build the project after a git clone. What would you prefer?

Thanks, Adriaan

**Comment by colindaven** [comment]
Hi Adriaan,

thanks for the quick reply. Can you please put the JAR on an FTP/dropbox/google etc or email to colindaven []AT]] hotmail [dot] com

Thanks!
Colin
