### ISSUE TITLE
Genotype Harmonizer an option to drop A/T C/G altogether

### ISSUE THREAD

**Issue by gaow** [molgenis/systemsgenetics#475]
I wonder if we can add to Genotype Harmonizer an option to drop A/T C/G altogether. This will result in the most conservative solution but can be useful in circumstances. It is not hard to filter it out later but it would be nice to have GH providing an option for it. Or any combination of existing switches can effectively give the desired result (eg very conserved re-aligning criteria)?

Thanks a lot for providing these great software utilities to the community!

**Comment by PatrickDeelen** [comment]
We have released a new version of Genotype Harmonizer with the --ambiguousSnpFilter option to exclude all A/T and G/C variants. 

https://github.com/molgenis/systemsgenetics/wiki/Genotype-Harmonizer-Download

Best of luck with your analyses.

**Comment by gaow** [comment]
Thank you Patrick, this is of great help!
