### ISSUE TITLE
Genotype Harmonizer --hweFilter minimum p-value?

### ISSUE THREAD

**Issue by juliedwhite** [molgenis/systemsgenetics#489]
Hi,

First...this program saves me **so much time** and is a godsend. Thank you!. 

Second...I'm having some trouble with using Genotype Harmonizer's --hweFilter. I am trying to harmonize the X chromosome and have 684 people (414 males, 270 females, all unrelated) and 15019 SNPs (genotyping rate 0.992001). Here's what I'm running: 

`java -Xmx1g -jar "~/GenotypeHarmonizer-1.4.20/GenotypeHarmonizer.jar" $*`
`--input ADNI1_chr23`
`--ref "~/1000G_Phase3_VCF/ALL.chrX.phase3_shapeit2_mvncall_integrated_v1b.20130502.genotypes.vcf.gz"`
`--refType VCF`
`--mafFilter 0.05`
`--hweFilter 0.01`
`--update-id`
`--mafAlign 0`
`--debug`
`--update-reference-allele`
`--outputType PLINK_BED`
`--output ADNI1_chr23_Harmonized_MAF_HWE`

This gives me: 
"Error in alignment: No variants where found in the input genotype data. Please check your variant filter options"

If I run with --hweFilter 0 or without that line at all, it runs fine and I'm left with 11249 SNPs.

So, I used plink to check my HWE values with: 
`plink --bfile ADNI1_chr23 --maf 0.05 --hardy --hwe 0.01 --make-bed --out ADNI1_chr23_Filter` 
which removes 2510 variants because of the MAF filter and 146 variants because of HWE. 

I'm mostly confused by the large SNP discrepancy in what is being removed because of HWE, but also partly confused by the wording here (I've been working at this for a while, so I might be going in circles at this point)...but does "the minimum hardy weinberg equilibrium p-value to include variant' mean that nothing is included _below_ that minimum? Or that a variant must have a p-value below that minimum _to be included_?

Regardless...can you help me figure out why this discrepancy? HWE tests using the X chromosome alone are variable...so maybe I shouldn't be doing this at all? 

Thank you! 
Julie

**Comment by PatrickDeelen** [comment]
Dear Julie,

First of, thank you for kind words.

As for your question, The HWE filter is a minimum value the p-value must have. I suspect GH struggles with the HWE calculations on the X chromosomes. I recommend doing the HWE filter using plink and then the harmonization using GH.

Best of luck.

Regards Patrick

**Comment by juliedwhite** [comment]
Hi Patrick, 

Thanks for your answer - that's what I ended up doing. 

Best,
Julie
