### ISSUE TITLE
Is it possible to get the output of GenotypeHarmonizer as VCF ?

### ISSUE THREAD

**Issue by drveera** [molgenis/systemsgenetics#491]
I see that there is no VCF option for `--outputType ` in GenotypeHarmonizer. Is it possible to add that option? I am using input VCF dosage file and I want the output to be in the same format. 

Thanks for this fantastic software.

Regards
Veera

**Comment by PatrickDeelen** [comment]
Dear Veera,

Sorry, at the moment we have no plans to add a VCF writer.

Regards Patrick
