### ISSUE TITLE
Eosinophils

### ISSUE THREAD

**Issue by antgomo** [molgenis/systemsgenetics#554]
Hi, in the web application the Eosinophil cell type is included but not in the package

Are you going to include it in future releases??

Thanks

**Comment by npklein** [comment]
Hi Antogomo,

Which web page did you use? https://molgenis79.gcc.rug.nl/deconvolution/ does not give eosinophils in the results, as we don't have it in our model. We are not planning to include this in future releases, as the training dataset (500FG)  does not include eosionphil concentrations.
