### ISSUE TITLE
Clarifying the license?

### ISSUE THREAD

**Issue by tomsing1** [molgenis/systemsgenetics#562]
https://github.com/molgenis/systemsgenetics/blob/54d08a45f7b7dd5f7980786f624fefaff209f418/Decon2/DeconCell/DESCRIPTION#L10

Awesome work! Would you mind clarifying the license you would like to share these packages under? For examples there are a couple of commonly used licenses for [CRAN](https://cran.r-project.org/web/licenses/) packages. Maybe one of those fits your needs?

**Comment by npklein** [comment]
Thank you for notifying us about the missing license!
 We have added GNU Lesser General Public License v3.0 in https://github.com/molgenis/systemsgenetics/pull/564
