### ISSUE TITLE
decon-eQTL genotype file

### ISSUE THREAD

**Issue by mooreann** [molgenis/systemsgenetics#577]
What format is the genotype file used in decon-eQTL suppose to be? I've tried .vcfs and plink2 genotype files but both give me the following error 

'does not have the same number of columns as there are in the header at row 1'

**Comment by npklein** [comment]
It should be a tab delimited dosage table with on the column samples, on the rows SNPs, and genotypes encoded as 0, 1, or 2 (the interaction effect will be reported relative to the allele that is coded as 2). See [https://github.com/molgenis/systemsgenetics/blob/master/Decon2/example_data/fake_genotype_dosages.txt](https://github.com/molgenis/systemsgenetics/blob/master/Decon2/example_data/fake_genotype_dosages.txt) for an example file.
