### ISSUE TITLE
Decon-eQTL: Expression file needing snp?

### ISSUE THREAD

**Issue by mooreann** [molgenis/systemsgenetics#579]
I'm trying to run Decon-eQTL for a whole genome, breaking up the runs by genes, so each run has a snp file of one gene and all its corresponding snps (genotype and expression files are broken up by chromosome). When I run one now I'm getting the coloring error:

Processed 0 gene-SNP pairs - 00:00:00:000 - skipped 0 gene-SNP combinations
Error: Genotype chr1:796338:T:C included in gene/snp combinations to test, but not available in the expression file!
Exception in thread "main" java.lang.RuntimeException: Error: Genotype chr1:796338:T:C included in gene/snp combinations to test, but not available in the expression file!

I checked the genotype file to ensure that snp was in it and it was, and checked that the corresponding gene was in my expression file, but it looks like the snp file may be the issue considering it processed 0 gene-SNP pairs.

As for the snp file format, here's a header of one of them (tab separated) as an example:
GENEID  SNPID
ENSG00000238284.2       chr7:41661765:C:A
ENSG00000238284.2       chr7:41662670:G:A
ENSG00000238284.2       chr7:41662736:C:T
ENSG00000238284.2       chr7:41663058:G:A
ENSG00000238284.2       chr7:41663704:A:C
ENSG00000238284.2       chr7:41665968:T:C
ENSG00000238284.2       chr7:41666014:T:C
ENSG00000238284.2       chr7:41666534:T:G
ENSG00000238284.2       chr7:41667078:T:A
ENSG00000238284.2       chr7:41667623:T:C

Ever seen this before?

**Comment by npklein** [comment]
Hi Mooreann, 

Usually when I get this error the SNP in the --snpsToTest file is not included in the genotype file, so since you checked that it is included in the genotype file I'm not sure what the problem is. Is it possible to subset your data and upload an example set?
