### ISSUE TITLE
Decon-eQTL dosage and snpsToTest

### ISSUE THREAD

**Issue by cindywen96** [molgenis/systemsgenetics#595]
I have a few questions running Decon-eQTL:
1. Should the genotype dosage file contain only the SNPs in snpsToTest? And the SNPs should be in the same order?
2. If in snpsToTest file, I have
```
Gene snp
Gene1 SNP1
Gene2 SNP1
```
Then in the dosage file, I'll just have the first two lines the same?
Thank you!

**Comment by npklein** [comment]
No, the genotype dosage file can also contain SNPs that are not in the snpsToTest file. They do not have to be in the same order. If you want for example to test the same SNP for multiple genes (or multiple SNPs for the same gene), you can do 

```
Gene      snp
Gene1    SNP1
Gene2   SNP1
Gene1   SNP5
Gene1   SNP3
```
while having only 1 entry for Gene1 in you expression file, and 1 entry for SNP1 in your dosage file.

The columns in the dosage and expression file do have to be in the same order, and that order also has to be the same in the cell counts file.

**Comment by npklein** [comment]
Yes
