### ISSUE TITLE
Chromosome X

### ISSUE THREAD

**Issue by DanielEWeeks** [molgenis/systemsgenetics#601]
Most analysis programs are developed first for autosomal data, and then later generalized/adjusted to work on X data.

We are applying Genotype Harmonizer to X chromosomal data in the pseudo-autosomal regions (PAR) and non-PAR region, and were wondering if Genotype Harmonizer's algorithms handle chromosome X data properly?  There doesn't seem to be a switch to inform it that it is analyzing X chromosome data instead of autosomal data.

Thank you,
Dan Weeks

**Comment by PatrickDeelen** [comment]
Dear Dan,

In principle Genotype Harmonizer will handle chr X files correctly. However, the LD based strand alignment is not available for chr X. 

Patrick
