### ISSUE TITLE
Decon-eQTL

### ISSUE THREAD

**Issue by TatiKarp** [molgenis/systemsgenetics#642]
Hello, 
thank you for a very nice tool.

I have a question regarding the input files for Decon-eQTL java tool.
In your example file "fake_genotype_dosages.txt" the first line starts with a tab, as well as "predicted.cellcounts.scaled.txt" first line.

Is it crucial to have the first column name empty? Is it also the case for the "count.table.simulated.txt"?

Thank you

**Comment by npklein** [comment]
Apologies for the confusion, it does indeed work both ways.
