### ISSUE TITLE
gene_network_decomposition.py

### ISSUE THREAD

**Issue by biopig** [molgenis/systemsgenetics#669]
I have found some errors in the `genenework_decomposition. py` script of `GeneNetwork Analysis`, such as the appearance of the `samples` parameter and the missing `--fastica_stable_safeIntermediate`.

In addition, I would like to know what the format of the expression matrix is and if it is possible to list the first few rows and columns.

**Comment by PatrickDeelen** [comment]
Thank you for your feedback. Please note that the fastica functions are not published and where only used in the past for some internal testing. We are therefore unable to provide support.
