### ISSUE TITLE
how to extract the expression numerical matrix of SNPS?

### ISSUE THREAD

**Issue by ChaoXianSen** [molgenis/systemsgenetics#672]
java -jar GenotypeHarmonizer.jar \
        -i ./all.sample.raw.snp.vcf.gz \
        -I VCF \
        -O TRITYPER \
        -o GenotypeHarmonizer \
        -mf 0.05 -ip 0.4 -asf

![image](https://github.com/user-attachments/assets/43e172ce-91e3-439c-918a-959bbbbdadf6)

Are there any tools or methods for extracting the expression numerical matrix of SNPS ? 
Expression value matrix was extracted for subsequent mediation analysis.
Looking forward to reply, thank you!

**Comment by PatrickDeelen** [comment]
You can try -O TABLE to get the dosages.

**Comment by ChaoXianSen** [comment]
Thank you for your reply!
![image](https://github.com/user-attachments/assets/a62f49aa-51a3-4f24-9382-53da325b9945)
![image](https://github.com/user-attachments/assets/f2cb7e83-0754-4d5a-98c0-773d21bd6c4e)

What are the rules of mutation site conversion, how is it converted to numerical values ？

Looking forward to reply again, thank you!

**Comment by PatrickDeelen** [comment]
These are genotype dosages in the sense they are also used by other formats, ie the count of the alternative allele and -1 for missing.
